### ISSUE TITLE
Display token in API UI 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#100]
### Describe the problem

Need to dynamically create and store the API token for the new user [as shown in UI here.](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=165-137&mode=dev)

### Proposed solution

Integrate with Firebase re: #73

**Comment by emmambd** [comment]
@davidgamez We had a discussion about if we're displaying the refresh token or the API key in the UI. The team couldn't remember if we came to a decision or not on this. Knowing this will help inform changes to the UI display. cc @qcdyx @cka-y

**Comment by davidgamez** [comment]
> @davidgamez We had a discussion about if we're displaying the refresh token or the API key in the UI. The team couldn't remember if we came to a decision or not on this. Knowing this will help inform changes to the UI display. cc @qcdyx @cka-y

We didn't get to an agreement as there were concerns about how we would be implementing an endpoint to serve the refresh request. I suggest keeping it just the refresh token for now. I'll make a list of the pros and cons of each approach so we can make a more informed decision.

**Comment by davidgamez** [comment]
Blocked by #118
