### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#114]
### Describe the problem

We need to do extensive integration testing with a populated DB.

In particular filtering.

### Proposed solution

Create a mini manual test plan and execute it.

**Comment by cka-y** [comment]
Tasks:
- [ ] Investigate possible implementation/frameworks
- [ ] Focus on provider, country code and municipality filtering
- [ ] Create/update a github action that runs the integration tests on QA on merge to main
- [ ] Create/update a github action that runs the integration tests on QA on release to main
