### ISSUE TITLE
Decide approach to storing API keys for authenticated GTFS Schedule feeds

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#123]
This will unblock storing historical datasets for authenticated GTFS Schedule feeds

Relates to #17 

PRs where we added ability to store authenticated feeds: 

https://github.com/MobilityData/mobility-database-catalogs/pull/188
https://github.com/MobilityData/mobility-database-catalogs/pull/61

**Winner: 1Password + GH actions + SM**

**Comment by davidgamez** [comment]
Clarify:
- [ ] Where the credentials will be saved and how the batch processes function access them
- [ ] Define a process to update credentials

**Comment by qcdyx** [comment]
Store API Keys:

1. Google Secret Manager
Using Google Secret Manager to store API keys is a secure and recommended practice, but it's not completely free.
Pricing: https://cloud.google.com/secret-manager/pricing

2. Environment Variables
We can store API keys as environment variables. However,  environment variables are not the most secure option, and managing them can be challenging as the application scales.

3. Configuration Files
Store API keys in configuration files ensures that these files are secure and not accessible to unauthorized users. We can consider encrypting the configuration files for an added layer of security.

**Comment by qcdyx** [comment]
How to add a key in Google Secret Manager?
Go to the Google Cloud Console:
Open the [Google Cloud Console](https://console.cloud.google.com/).

Navigate to Secret Manager:
In the Cloud Console, navigate to the Secret Manager page.

Create a New Secret:

Click on the "Create Secret" button.
Provide a name for your secret.
Add a New Version:

After creating the secret, click on the secret's name.
Click on the "Add Version" button.
Add API Key as a Secret Payload:

In the new version, you can add the API key as the secret payload.
Click on "Add Secret Data" and provide the key-value pair for your API key.
Save the Version:

Save the changes, and this will create a new version of the secret with the API key.

**Comment by qcdyx** [comment]
https://support.1password.com/scim-deploy-gcp/

**Comment by qcdyx** [comment]
Vote
1. 1Password + GH actions + SM
2. 1Password + 1Password API 
3. SM
4. SM GH actions + GH secrets
5. DB + SM

**Comment by emmambd** [comment]
Completed.
