### ISSUE TITLE
Batch process for adding new GTFS feeds (Schedule + Realtime)

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#16]
## **User Story**

As an API consumer, I need to access new GTFS and GTFS Realtime feeds that added to the Mobility Database Github repo so I can discover new data. 

## **Acceptance Criteria**

- A batch process that automatically stores new GTFS feeds from the Mobility Database Github repo that with all authentication types. Includes both GTFS Schedule and Realtime feeds.
- Batch process should include all the steps for unauthenticated GTFS feeds and GTFS realtime outlined in [this flowchart](https://miro.com/app/board/uXjVM86LB1s=/?moveToWidget=3458764558857335430&cot=14)
![Public  Mobility Database API_ User Story Mapping - Flowchart for adding new feeds (1)](https://github.com/MobilityData/mobility-feed-api/assets/90632321/d03aa727-9929-48eb-9893-e3bac68bbfc7)

- Batch process should include all the steps for updating feeds outlined in [this flowchart](https://miro.com/app/board/uXjVM86LB1s=/?moveToWidget=3458764558860655921&cot=14)
![Public  Mobility Database API_ User Story Mapping - Flowchart for updating feeds](https://github.com/MobilityData/mobility-feed-api/assets/90632321/fe03e23a-f449-4d9c-a145-f1f0982f4d11)

## **Materials**

- [Current cronjob for storing latest datasets in the Mobility Database catalogs](https://github.com/MobilityData/mobility-database-catalogs/blob/main/.github/workflows/store_latest_datasets_cronjob.yml)

## **Considerations and Materials**

- [PR that added GTFS feed workflows to the Mobility Database catalogs repo](https://github.com/MobilityData/mobility-database-catalogs/pull/61)

**Comment by davidgamez** [comment]
Tasks:
- [ ] How to implement batch processing
- [ ] Define/clarify ETL for all fields
- [ ] Review current Github action that generates sources.csv, https://github.com/MobilityData/mobility-database-catalogs/blob/main/.github/workflows/export_to_csv.yml

**Comment by cka-y** [comment]
Needs #196 to be merged

**Comment by davidgamez** [comment]
Tasks:
- [ ] Create GitHub action on the _mobility-feed-api_ that gets triggered by the database merge event. The script _"run"_ the populate script
- [ ] Create  a GCP secret key for the authenticated feeds
