### ISSUE TITLE
Improve documentation experience with Redocs

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#160]
### Describe the problem

Swagger isn't always intuitive to use to peruse documentation and test. We want an extensible, open source docs platform we can use to provide more detailed instructions if needed in the future, and also include examples of how the API is being used by the community.

### Proposed solution

This is not a replace for OpenAPI, this enhance the documentation potentially replacing Swagger UI, here the links
A basic example with our spec https://redocly.github.io/redoc/?url=https://mobilitydata.github.io/mobility-feed-api/DatabaseCatalogAPI.yaml (We will be hosting this not redocly)
Full Petstore example https://redocly.github.io/redoc/
Github tool repository https://github.com/Redocly/redoc

**Comment by jcpitre** [comment]
Investigated redoc. 
Apparently the `try me` feature is not available with the free open source version. 
https://github.com/wll8/redoc-try?tab=readme-ov-file did a version redoc using swagger for the `try me` part. But I am not too keen on an hybrid version like this.
Plus it does not seem too easy to integrate redoc within the github page of mobility-feed-api. We could do a complete installation or redoc off-line, then commit this to the mobility-feed-api repo, but IMO it would only pollute mobility-feed-api. (actually the swagger code is currently committed within mobility-feed-api (docs/SwaggerUI), and we should look into getting it out of there.
