### ISSUE TITLE
Batch process for storing historical datasets from a GTFS authenticated feed

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#172]
[Flowchart here](https://miro.com/app/board/uXjVM86LB1s=/?moveToWidget=3458764570427336588&cot=14) (to be updated with decision from #123)

For GTFS Schedule feeds, storing historical datasets need to work for GTFS feeds that require authentication. 

[Current Github Action](https://github.com/MobilityData/mobility-database-catalogs/blob/c496a6384542581fe926b75f9d7a5cd09dbe6535/.github/workflows/add_new_or_updated_feeds.yml#L41)

**Comment by cka-y** [comment]
Needs #196 to be merged

**Comment by davidgamez** [comment]
Tasks:

**Comment by davidgamez** [comment]
Tasks:
- [ ] Decide on how to consume the credentials (#123)
- [ ] Create a Secret key with API creds and give access to the downloader function
- [ ] Modify function to download authenticated feeds

**Comment by davidgamez** [comment]
depends on #16
