### ISSUE TITLE
re: #169 new script for extracting bounding box

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#173]
Introduce new functions : one responsible for extracting the bounding box from a dataset_id. From bug discovered in #169 

[Current script on the catalogs is here](https://github.com/MobilityData/mobility-database-catalogs/blob/fe9e68850fc8c81c43df5bfd52125fc5ba64f99a/tools/helpers.py#L250)

**Comment by davidgamez** [comment]
Tasks:
 - [ ] Review the current bounding box extracting script from GH actions
 - [ ] Create a GCP function that extracts the bounding box from a dataset
 - [ ] Trigger the created function after a dataset is created on the DB
