### ISSUE TITLE
Add Apple ID as SSO option to registration flow

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#178]
Include Apple ID as an SSO registration option.

**Comment by cka-y** [comment]
Tasks:
- [ ] Include Apple ID as an SSO registration option

**Comment by davidgamez** [comment]
@fredericsimard, please connect with @qcdyx to help set up the sign-in with Apple. Here is the documentation: 
- https://firebase.google.com/docs/auth/ios/apple
- https://developer.apple.com/help/account/configure-app-capabilities/configure-sign-in-with-apple-for-the-web

**Comment by fredericsimard** [comment]
@davidgamez Yes sir! 🫡

@qcdyx Before we can begin, we'll need the Firebase project ID, the complete list of URLs (including sub-domains) and return URLs.

>Provide your web domain and return URLs that will support Sign in with Apple. Your website must support TLS 1.2 or higher. All Return URLs must be registered with the https:// protocol included in the URI string.
