### ISSUE TITLE
Bounding box modifications

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#184]
- Modify `boundingLatitudes` and `boundingLongitudes` in /v1/gtfs-feeds endpoint in Swagger docs to `datasetLatitudes` and `datasetLongitudes`. Description should state these values come from the latest dataset. 
- Display bounding box in the latest dataset object for the feed endpoint response
- Remove bounding box filters from the dataset endpoint 
- Keep bounding box in dataset response as is

**Comment by indraneel** [comment]
@emmambd can you clarify that this means the bounding box filtering will be moving from datasets to feeds?

**Comment by emmambd** [comment]
@indraneel "Keep bounding box in dataset response as is" means that we're still including bounding box filtering in the dataset response, but there's additional work to add the info to the feeds response as well.

**Comment by aronza** [comment]
Hi @emmambd ,

In the description, the names of the new variables are datasetLatitudes  and datasetboundingLongitudes. Is the bounding in the former a typo or intentional? Shouldn't they follow the same convention?

**Comment by aronza** [comment]
Also are we keeping the same variables in `/v1/gtfs_feeds/{id}/datasets` the untouched, and only changing `/v1/gtfs_feeds`?

**Comment by emmambd** [comment]
> Hi @emmambd ,
> 
> In the description, the names of the new variables are `datasetLatitudes` and `datasetboundingLongitudes`. Is the bounding in the former a typo or intentional? Shouldn't they follow the same convention?

@aronza I've updated the description to fix this - they should follow the same convention as `datasetLatitudes` and `datasetLongitudes`. Let me know if you have any other outstanding questions!
