### ISSUE TITLE
Add static content pages to website

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#185]
Composites of Mobility Database website pages to replace the content on database.mobilitydata.org: 

- [Homepage](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=606-441&mode=dev)
- [About](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=753-6391&mode=dev)
- [FAQ](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=753-6391&mode=dev)
- [Contribute a Feed](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=660-1324&mode=dev)

**Comment by cka-y** [comment]
Tasks:
- [ ] Home Page
- [ ] About
- [ ] FAQ
- [ ] Contribute a Feed

**Comment by emmambd** [comment]
@cka-y - Just noting here that there are some edits to the Contribute a Feed text to expect. I'll add them on Friday to the comp.
