### ISSUE TITLE
Bounding box filtering does not work

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#189]
### Describe the bug

Filtering by bounding box does not work.
Tried with filtering on feed and fioltering on datasets.

### Steps/Code to Reproduce

As an example let's query datasets of the mdb-2 feed (Headers omitted):
`curl -X 'GET' 'https://api-qa.mobilitydatabase.org/v1/gtfs_feeds/mdb-2/datasets'`
```
[
  {
    "id": "mdb-2",
    "feed_id": "mdb-2",
    "hosted_url": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/ca-ontario-london-transit-commission-gtfs-2.zip?alt=media",
    "note": null,
    "downloaded_at": "2022-02-22T19:51:34",
    "hash": null,
    "bounding_box": {
      "minimum_latitude": 42.905244,
      "maximum_latitude": 43.051188,
      "minimum_longitude": -81.36311,
      "maximum_longitude": -81.137591
    },
    "components": []
  }
]
```

Now let's specify a bounding box that is clearly completely outside the longitude and latitude of the dataset, e.g. 10,20 and 10,20:
```
curl -X 'GET' \
  'https://api-qa.mobilitydatabase.org/v1/gtfs_feeds/mdb-2/datasets?boundingLatitudes=10%2C20&boundingLongitudes=10%2C20&boundingFilterMethod=completely_enclosed'
```
I still get the same dataset. The returned array should be empty.
So maybe there's an error in the way the boundaries are specified. Some inversion. So if I select `disjoint` I should have the complement to that result I had before, right?
```
curl -X 'GET' \
  'https://api-qa.mobilitydatabase.org/v1/gtfs_feeds/mdb-2/datasets?boundingLatitudes=10%2C20&boundingLongitudes=10%2C20&boundingFilterMethod=disjoint'
```
I still get the same dataset.

Let's try to be positive and give a bounding box that really encloses the dataset. Latitude 42,44 and longitude -82,-81, and use disjoint so it should not return the dataset (since it is actually enclosed in the provided boundaries):
```
curl -X 'GET' \
  'https://api-qa.mobilitydatabase.org/v1/gtfs_feeds/mdb-2/datasets?boundingLatitudes=42%2C44&boundingLongitudes=-82%2C-81&boundingFilterMethod=disjoint' 
```
Again get get the same dataset.
Maybe the order of longitudes is wrong? Let's try with -81,-82:
```
curl -X 'GET' \
  'https://api-qa.mobilitydatabase.org/v1/gtfs_feeds/mdb-2/datasets?boundingLatitudes=42%2C44&boundingLongitudes=-81%2C-82&boundingFilterMethod=disjoint'
```
Again I get the same dataset.

### Expected Results

See Above

### Actual Results

See above

**Comment by jujiang526** [comment]
Those example curl requests seem to have the wrong parameters. For example boundingFilterMethod should be bounding_filter_method.

The following examples work locally:

a completely outside box using `complete_enclosed` 
`curl -X "GET" \
"http://localhost:8080/v1/gtfs_feeds/mdb-2/datasets?latest=true&offset=0&bounding_latitudes=10%2C20&bounding_longitudes=10%2C20&bounding_filter_method=completely_enclosed" -H "accept: application/json"`
Nothing returned

a completely outside box using `disjoint` 
`curl -X "GET" \
"http://localhost:8080/v1/gtfs_feeds/mdb-2/datasets?latest=true&offset=0&bounding_latitudes=10%2C20&bounding_longitudes=10%2C20&bounding_filter_method=completely_enclosed" -H "accept: application/json"`
Got the dataset

I do agree that the implementation of "completely_enclosed" filtering is wrong. I read the documentation again and the bounding box in the query is supposed to enclose the bounding box of the actual dataset, while I did the opposite. Will put a fix for this.

**Comment by jcpitre** [comment]
In that case we need to change the yaml files since they specify `boundingLatitudes`, `boundingLongitudes` and `boundingFilterMethod`.
It's actually a good thing to change them since using camelCase is not consistent with the other parameters that use snake_case.
