### ISSUE TITLE
Set internal access on GCP to prevent hacking attempts

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#192]
**Problem**

There are many (unsuccessful) hacking attempts to access our PostGres database that are indirectly impacting performance. 

**Possible Solution**

Set internal access only to our PostgreSQL database on GCP to prevent so many hacking attempts.

**Comment by cka-y** [comment]
Proposed solution:
- [ ] Create VPC connector
- [ ] Restrict database connection to private VPC
- [ ] Modify the terraform script for the api, dataset batch processing and user api to be able to connect to the database through the VPC connector

**Comment by cka-y** [comment]
Needs #196 to be merge before modifying the dataset batch processing access to the VPC connector

**Comment by cka-y** [comment]
Needs #210  to be completed
