### ISSUE TITLE
Combine the two openapi files DatabaseCatalogAPI.yaml and DatabaseCatalogAPI_IAP.yaml

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#203]
### Describe the problem

These two files differ only by one line for the the type of authentication. 
DatabaseCatalogAPI.yaml is for the public interface and DatabaseCatalogAPI_IAP.yaml is used internally after requests have been processed by the dispatcher.

### Proposed solution

Both files could be combined in a _source_ file and recreated during the build process by substituting the authentication line.

**Comment by Neo2308** [comment]
Would it be okay to do this using yq? Or should we prefer a sed route?

**Comment by jcpitre** [comment]
I would prefer sed, but yq would be ok if it's simple to understand for a neophyte.

**Comment by jcpitre** [comment]
Duplicate of #146
