### ISSUE TITLE
Migrate DEV PostgreSQL database to QA PostgreSQL instance

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#210]
# Description

PostgreSQL DEV and QA are deployed independently in their own GCP environment. Either both instances have low usage. We propose deploying both schemas in the same DB instance to save on cost and unnecessary running resources. 

# Proposed Solution

Delete the PostgreSQL DEV instance and create a new schema under the QA PostgreSQL instance. Update all DEV functions to point to the new DEV schema on QA environment.

**Comment by cka-y** [comment]
Tasks:
- [ ] Update API env variable retrieval to use GCP secret manager
- [ ] Update dev database to be in QA environment with a different database name
- [ ] (Optional) Update QA database name to be consistent with dev
- [ ] Test that the API as well as the batch processing cloud functions can correctly access the new database in dev
