### ISSUE TITLE
Update sqlacodegen to 3.0.0rc3

### ISSUE THREAD

**Issue by Neo2308** [MobilityData/mobility-feed-api#213]
### Describe the problem

There is an incompatibility notice for python 3.11 https://github.com/MobilityData/mobility-feed-api#python-311-incompatibility-notice

### Proposed solution

The issue seems to be resolved with the latest release candidate of sqlacodegen

**Comment by davidgamez** [comment]
Hi @Neo2308, I updated sqlacodegen to 3.0.0rc3 locally, and I had issues generating the models with no clear path to fix. Also, I tried 3.0.0rc2 and came across other generation issues related to the geometry type. I suggest waiting until the 3.0.0 is officially released; it should be more stable.
