### ISSUE TITLE
Create Event Filtering Trigger Function

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#225]
### Describe the problem

As part of processing the validation report, we need a function that listens to files created on a specific GCP bucket and sends an event to one or multiple pub-sub subscriptions, depending on a configuration list.

### Proposed solution

Develop a Google Cloud Platform (GCP) function designed to monitor the datasets bucket. This function will maintain a collection of regex patterns and corresponding Pub/Sub addresses. When a new file is added to the GCP bucket, the function will compare the filename against the stored regex patterns, identifying matches. Subsequently, the function will send events to the relevant Pub/Sub queues based on the identified matches.

**Comment by emmambd** [comment]
@cka-y @davidgamez Can we close this one?

**Comment by davidgamez** [comment]
> @cka-y @davidgamez Can we close this one?

Yes, we abandon this idea in favor of the built-in Eventarc feature from GCP.
