### ISSUE TITLE
Implement OpenApi schema changes to support validation reports

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#226]
### Describe the problem

As outlined in #223, implement the OpenAPI schema changes to facilitate the integration of validation reports.

### Proposed solution

Add the validation report summary to the gtfs datasets on the endpoints `/v1/gtfs_feeds/{id}/datasets` and `/v1/datasets/gtfs/{id}` as described in #223.

**Comment by indraneel** [comment]
Schema changes in #224 can be seen here https://github.com/MobilityData/mobility-feed-api/pull/224/files

**Comment by indraneel** [comment]
Todo:

- [ ] design SQL Schema for validation report data
- [ ] python code for returning validation report data via API

**Comment by emmambd** [comment]
@jujiang526 Examples of validation report JSON from https://gtfs-validator.mobilitydata.org/

[MBTA feed validation report](https://gtfs-validator-results.mobilitydata.org/970303fe-7435-4c74-87c8-344aaf05277f/report.json)
[SEPTA feed validation report](https://gtfs-validator-results.mobilitydata.org/79dd7b34-d1f3-4a16-af19-c74b82c7be6d/report.json)

Let me know if you're looking for specific use cases.

**Comment by emmambd** [comment]
Completed in #244
