### ISSUE TITLE
Update Database with validators report

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#229]
### Describe the problem

As part of the Datasets metadata, we would like to include a summary of the information produced by the [GTFS validator](https://github.com/MobilityData/gtfs-validator). This issue implements the update of the MobilityData Database after a validation report is generated. 

Depends on #228

### Proposed solution

After #228 is implemented, a validation report is generated and copied to the target GCP bucket. Using [Eventarc](https://cloud.google.com/eventarc/docs) trigger.

**Comment by cka-y** [comment]
Tasks:
- [ ] Use Eventarc to trigger Cloud Function when report is uploaded
- [ ] Populate database report related entities
