### ISSUE TITLE
[style/cleanup] make everything snake_case and remove filter/sort params

### ISSUE THREAD

**Issue by indraneel** [MobilityData/mobility-feed-api#238]
### Describe the problem

Some labels or names in `DatabaseCatalogAPI.yaml` are in camelCase and others in snake_case. 

### Proposed solution

Make everything snake_case. e.g. latestQueryParam -> latest_query_param. Even if it's not customer facing, making things uniform 

Also
- remove filter parameter
- remove sort parameter in the yaml and python code

**Comment by indraneel** [comment]
@jcpitre I wrote this out without asking you: did you mean this `filter` parameter https://github.com/MobilityData/mobility-feed-api/blob/main/docs/DatabaseCatalogAPI.yaml#L623?

**Comment by emmambd** [comment]
Closed with #290
