### ISSUE TITLE
Modify OpenAPI Schema so the "live" version of the API docs doesn't include the validation report metadata

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#239]
### Describe the problem

We need some way to separate out "draft" schema changes from those that represent the V1 of the API that users can rely on. 

### Proposed solution

New version of the Open API schema that has a label of [DRAFT v1.1]?

**Comment by jcpitre** [comment]
We decided that we would keep the implementation with the ValidationReport section and just document it as not supported for now.
