### ISSUE TITLE
Add load test to GitHub Actions

### ISSUE THREAD

**Issue by qcdyx** [MobilityData/mobility-feed-api#248]
### Describe the problem

Create a new file in your repository under the .github/workflows/ directory, for example, load-test.yml and define load test GitHub Actions workflow.

### Proposed solution

Create or add to an existing GH action the load tests using the cli

**Comment by cka-y** [comment]
Tasks:
- [ ] Add documentation on running the load tests
- [ ] Create github action that runs load tests in QA on merge
