### ISSUE TITLE
Troubleshoot why first account verification email doesn't work for oAuth registered accounts

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#280]
To recreate: 

- Create an account on [the Mobility Database](https://beta.mobilitydatabase.org/) with either Github or Google. 
- Submit registration form 
- Check email for verification email
- Email is not sent 
- Resend email
- You should receive email

**Comment by jcpitre** [comment]
Tasks:

- [ ] Investigate. It could be missing from the login with provider saga. It might be different for different providers.
- [ ] Fix

**Comment by qcdyx** [comment]
Investigation:
GitHut is not a trusted Provider - that's why Email is not sent when signup with GitHut 
Google is a trusted Provider - that's why signup with Google doesn't require email re-verification and redirects user to complete-registration screen.

Sources: https://firebase.google.com/docs/auth/users#:~:text=Trusted%20providers%3A,and%20%40hotmail.com%20addresses)
Trusted providers:
Google (for @gmail.com addresses)
Yahoo (for @yahoo.com addresses)
Microsoft (for @outlook.com and @hotmail.com addresses)
Apple (always verified, because accounts are always verified and multi-factor-authenticated)
Untrusted providers:
Facebook
Twitter
GitHub
Google, Yahoo, and Microsoft for domains not issued by that Identity Provider
Email / Password without email verification

**Comment by qcdyx** [comment]
Found a new bug during my investigation:
If user's GitHub account doesn't provide an email address (1. there's no email associated with this account at all. 2. user doesn't display email as public) 
<img width="416" alt="image" src="https://github.com/MobilityData/mobility-feed-api/assets/5789435/a6f45fc4-e195-44a5-901b-265421befc8e">

1. User doesn't get an verification email.
2. An error occurred after user click Resend email.
<img width="709" alt="image" src="https://github.com/MobilityData/mobility-feed-api/assets/5789435/17efcbe6-5370-473f-8ba1-32998c27fff6">

**Comment by emmambd** [comment]
@qcdyx For the new bug, providing a more descriptive error would be sufficient here: 

e.g "no email provided in Github account"

**Comment by davidgamez** [comment]
> @qcdyx For the new bug, providing a more descriptive error would be sufficient here:
> 
> e.g "no email provided in Github account"

I think, in this case, we should not verify the email as it's not in the GitHub account(visible). The user will be stuck to this page forever.

**Comment by emmambd** [comment]
@davidgamez Agreed - the error should show up when they first try to use Github, rather than on the verification page.

**Comment by davidgamez** [comment]
> Investigation: GitHut is not a trusted Provider - that's why Email is not sent when signup with GitHut Google is a trusted Provider - that's why signup with Google doesn't require email re-verification and redirects user to complete-registration screen.
> 
> Sources: https://firebase.google.com/docs/auth/users#:~:text=Trusted%20providers%3A,and%20%40hotmail.com%20addresses) Trusted providers: Google (for @gmail.com addresses) Yahoo (for @yahoo.com addresses) Microsoft (for @outlook.com and @hotmail.com addresses) Apple (always verified, because accounts are always verified and multi-factor-authenticated) Untrusted providers: Facebook Twitter GitHub Google, Yahoo, and Microsoft for domains not issued by that Identity Provider Email / Password without email verification

This explains why the account don't get merged. However, it's interesting to know why re-sending email works and if it's possible to actually _automate it_, so the user don't need to click the button if it's not triggered by default.

**Comment by emmambd** [comment]
Error triggered when try to sign up with Github: 

"No public email provided in Github account. Please use a different registration method."
