### ISSUE TITLE
Add bounding box input validation from database

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#282]
Add bounding box input validation from database OR return empty response

Right now incorrect bounding box input generates a Server 500 error

GCP error:
insertId: "65ca707e00039d351ec834d1"
labels: {1}
logName: "projects/mobility-feeds-prod/logs/run.googleapis.com%2Fstderr"
receiveTimestamp: "2024-02-12T19:24:46.564239702Z"
resource: {2}
textPayload: "(Background on this error at: https://sqlalche.me/e/14/2j85)"
timestamp: "2024-02-12T19:24:46.236853Z"

**Comment by jcpitre** [comment]
Tasks:
- [ ] Add test to reproduce
- [ ] Investigate how sql reacts to invalid values
- [ ] Return HTTP error if coordinates don't make sense - Formatting Floating point (return error) and invalid value (return empty list)
