### ISSUE TITLE
Leaving transactions open generates 500 Server Error

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#283]
Parsing error from bounding box example in /gtfs-feeds

GCP error:
insertId: "65ca707e00039d351ec834d1"
labels: {1}
logName: "projects/mobility-feeds-prod/logs/run.googleapis.com%2Fstderr"
receiveTimestamp: "2024-02-12T19:24:46.564239702Z"
resource: {2}
textPayload: "(Background on this error at: https://sqlalche.me/e/14/2j85)"
timestamp: "2024-02-12T19:24:46.236853Z"

**Comment by jcpitre** [comment]
- [ ] Investigate where the transaction is opened
- [ ] Investigate how to open and close transactions properly
- [ ] Add a test to reproduce the problem - One request with invalid parameters - Bounding box with 2 hyphens, the second one valid
- [ ] Implement
