### ISSUE TITLE
Swagger documentation changes 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#284]
- Update gtfs_feeds example bounding box input to -78.58,-87.29 instead of -78.58,-87-29 (should check to see if this actually returns a feed example)
- Check all endpoint example “try it out” buttons  to make sure that they each return a full response
- Update terms of service link to mobilitydatabase.org/terms-and-conditions

**Comment by jcpitre** [comment]
`mobilitydatabase.org/terms-and-conditions` gives a 404 error

**Comment by jcpitre** [comment]
The same examples are used for gtfs_feeds and gtfs_rt_feeds queries, but they can't both return valid data with the same producer_url for example.
We will need to duplicate some of the parameter specifications so they go with gtfs_feeds or gtfs_rt_feeds

**Comment by emmambd** [comment]
@jcpitre It 404s because the page doesn't exist yet since we haven't done the redirect. Currently is https://beta.mobilitydatabase.org/terms-and-conditions

**Comment by emmambd** [comment]
@jcpitre Some suggestions of examples for the different endpoints now that I can test (no 500 error): 

/v1/feeds: 

producer_url: https://exo.quebec/
provider: Exo 

v1/feeds/{id}:

mdb-1921 

v1/gtfs-feeds:

mdb-1984 with its associated fields

v1/gtfs-feeds/{id}: 

mdb-1089 

/v1/gtfs-rt-feeds:

provider: Tri Delta Transit
producer_url: https://api.511.org
entity_types: vp, sa, tu

/v1/gtfs-feeds/datasets

(whatever GTFS feed in the database has several dataset downloads) 

v1/datasets/gtfs/{id} 

a dataset from the feed in /v1/gtfs-feeds/datasets
