### ISSUE TITLE
downloaded_at fixes

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#285]
- Fix downloaded_at filtering (currently doesn't work)

Current behavior: 

- Returns all datasets associated with feed id

**Comment by emmambd** [comment]
Tasks: 
- [ ] Fix downloaded_at filtering (remove 2 underscores in the code to make this work) 
- [ ] Update downloaded at queries from downloaded_at_gte and downloaded_at_lte to downloaded_before and downloaded_ after
- [ ] Includes datetime format in the description of both queries: e.g 2024-02-10T01:06:00Z

**Comment by davidgamez** [comment]
> In testing steps, make sure that we can do partial matches (e.g just the date with no timestamp)

@emmambd let's connect on this requirement as a datetime without timestamp like _2024-01-01_ is not a valid ISO 8601 format
