### ISSUE TITLE
Create a privacy policy screen

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#306]
# Description

Currently, the privacy policy link is pointing to the MobilityData website. This is blocking the approval of Google's OAuth authentication. In this issue, we must create a privacy policy screen with the content on https://mobilitydata.org/privacy-policy/.

**Comment by emmambd** [comment]
Tasks: 

- [ ] Create a page with Privacy Policy contents 
- [ ] Update Privacy Policy link in the footer and registration pages to link to this internal page instead
