### ISSUE TITLE
Setup Google Analytics tags on UI 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#311]
Setup Google Analytics tags on UI to track usage
Requirements:
- No DEV and local environment tags
- "?" QA environment tags

Review for environment setup https://support.google.com/tagmanager/answer/6311518?hl=en

**Comment by fredericsimard** [comment]
Here's the tag and the JS code to add:

`G-7J2LN19LE2`

```javascript
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7J2LN19LE2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7J2LN19LE2');
</script>
```

**Comment by davidgamez** [comment]
Tasks:
- Add GA script only for PROD. Verify if it's possible to have GA QA tag.
- _Test_ GA tag, reach out to @fredericsimard.

**Comment by fredericsimard** [comment]
@davidgamez If you can have one GA code be used in prod, and a different one in QA, then yes I can create a separate tag for the latter.

**Comment by fredericsimard** [comment]
Here is the QA version of the GA tag:

`G-ZJY1KRHNT2`

```javascript
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-ZJY1KRHNT2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-ZJY1KRHNT2');
</script>
```
