### ISSUE TITLE
Create API usage dashboard

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#312]
- Set up dashboard to easily see API traffic
- No deployment script(nice to have)
- Gather
  - Number of total requests
  - Number of requests per endpoint
  - ~Parameters usage per endpoint~
  - Number of unique active users per day

**Comment by davidgamez** [comment]
Tasks:
- Create a BigQuery table to store requests from the cloud run
– Create a clod run Log sink for the API exporting calls to BigQuery
- Create a dashboard(Google drive stats location) with the queries

**Comment by davidgamez** [comment]
Out of scope is the _Number of unique active users per day_ as it requires changes in the way the API generates the logs; this will be part of  #331.
