### ISSUE TITLE
Integration test failing on feeds endpoint filtering by municipality

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#319]
### Describe the bug

Integration tests are failing in QA and PROD while running `GTFSFeedsEndpointTests.test_filter_by_municipality_gtfs` with the following error:
```
AssertionError: Expected all feeds to have municipality 'Napoli', but found 
municipalities '['Indianapolis']'
```
The artifact of the integration test results has not been generated, making it hard to get the full report locally for further analysis.

Example failing build, [link](https://github.com/MobilityData/mobility-feed-api/actions/runs/8074913508/job/22078412827)
Current API version:
```
{
    "version": "v0.0.0",
    "commit_hash": "2c9d680b6547a180b1d3d4e9f2ccd88872d920c7"
}
```

### Steps/Code to Reproduce

- Execute integration test on the QA environment
- Verify that it is failing
- Verify that the integration test results artifact is not uploaded 

### Expected Results

- Integration test passed
- The integration test results artifact is generated even if the job fails

### Actual Results

- Integration test passed
- The integration test results artifact is not generated when the job fails

**Comment by jcpitre** [comment]
The integration test queries the Napoli municipality, but this returns feeds with municipalities names that contain Napoli, i.e. Indianapolis.
The test then checks for an exact match for Napoli, which fails.

Short term solution: Change the test to make sure the returned municipalities contain Napoli (not an exact match).
Longer term we should have a `exact_match` boolean parameter in the API. Or something to that effect.
