### ISSUE TITLE
Develop feeds endpoint

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#32]
## User Stories

- I want to fetch the full list of feeds from the Mobility Database, so I can get familiar with the schema and quickly discover what types of data are available. 
- I want to filter the feed list by status, so I can pull only the active feeds, test feeds in development, or check and update the inactive feeds in my app. 
- I want to search for specific providers in the feed list, so I can find the feeds I need to add, compare or analyze.
- I want to search for specific producer URLs, so I can search for feeds I already know of or have in my system easily.

## Acceptance Criteria

- Should return a list of feeds with all the fields that are common to all feed types, including when no parameters are specified [Example here](https://mobilitydata.github.io/mobility-feed-api/SwaggerUI/index.html#/feeds/get_feeds)

- Should be able to send the following optional parameters [(specified in Swagger)](https://mobilitydata.github.io/mobility-feed-api/SwaggerUI/index.html#/feeds/get_feeds): 

   - int `limit` 
   - int `offset`
   - string `filter`
      - filter options
          - enum `status`: options `active`, `inactive`, `development`, `deprecated`
              - feeds with an empty status field should be returned when the `status=active` 
          - contains string `provider`, e.g `"Kearns"`
          - contains string `producer_URL` e.g `"download.gtfs.de/germany/nv_free"`
   - string `sort`
         - sort options 
             - `external_id`

**Comment by jcpitre** [comment]
`filter` and `sort` have been delegated to this issue: https://github.com/MobilityData/mobility-feed-api/issues/63
