### ISSUE TITLE
Set feature flag system in place for working on the UI

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#329]
- Set feature flag system in place for working on the UI

**Comment by cka-y** [comment]
## Possible Feature Flag Systems Comparison
| Feature Flag System                       | Implementation Effort                                             | Cost                                                        | Scalability and Flexibility                                                                                    |
|------------------------------------------|------------------------------------------------------------------|------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| **Custom Feature Flag System**           | - Develop API endpoints for each environment.                    | - Server costs for hosting feature flag endpoints.         | - Basic feature flag functionality to start.                                                                   |
|                                          | - In-house development and maintenance required.                 | - Minimal storage costs for flags.                         | - Expansion to support A/B testing and complex flag types would require additional development.                |
| **Third-Party API (e.g., [PostHog](https://posthog.com/))**      | - Minimal setup: integrate API calls and configure access keys. | - Competitive pricing starts at [$150](https://www.statsig.com/pricing) - [$450](https://posthog.com/pricing)/month for our requirements | - Comprehensive suite of features, including A/B testing, user segmentation, and multivariate testing.         |
|                                          | - Swift implementation leveraging third-party expertise.        | services with an open-source option available.            | - Supports advanced flag configurations and real-time analytics.                                                |
| **Firebase Remote Config**               | - [Ready-to-use with Firebase's SDK.](https://firebase.google.com/docs/remote-config/get-started?platform=web&_gl=1*1jgwj8p*_up*MQ..*_ga*MTA4NTYwNDQ4NC4xNzEwMjQxNTcz*_ga_CW55HF8NVT*MTcxMDI0MTU3Mi4xLjAuMTcxMDI0MTc4My4wLjAuMA..)                              | - Included at [no extra charge](https://firebase.google.com/pricing#remote-config) with Firebase services.      | - Advanced targeting capabilities leveraging Firebase Authentication.                                           |
|                                          | - Quick integration for apps already using Firebase.             |                                                            | - Feature flags can be tied to user demographics, app versions, or custom audiences.                           |
|                                          |                                                                  |                                                            | - Ideal for mobile apps with the need for granular control over feature rollouts.                               |
