### ISSUE TITLE
Define API schema for search endpoint

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#350]
Implement a search endpoint to support searches on multiple feeds
a. Search returns multiple types of feeds(GTFS, GTFS-rt), and on the feed type, the resulting documents will have different structures.
b. Search will be done with OR across entities TBD
c. Search is not case-sensitive and allows partial matches.

Add a search endpoint (simple implementation with OR filtering), indexing to come later
- Indexing in SQL 
- API schema endpoint 
(See how it's done in TransitFeeds) 
- data type filtering 

Entities must be searchable by the following fields:
a. Feed: Feed.feedName
b. Feed: Feed.provider
c. Feed: with Location by Location.country_code, Location.subdivision_name and Location.municipality

**Comment by davidgamez** [comment]
Tasks:
- [ ] Propose API schema for search endpoint
- [ ] Review the feasibility of schema implementation. Describe the query plan.
- [ ] Check if the DB structure(index) needs to be changed to meet requirements.
