### ISSUE TITLE
Create add feed form fields and styling

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#361]
Right now, our [add a feed form](https://mobilitydatabase.org/contribute) is a long embed that isn't very intuitive. We want to update it to [what's in this design](https://www.figma.com/design/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?node-id=1370-1829&t=bM8RSabLB5sFWYq9-1). 

Design updated in alignment with usability feedback. 

**Definition of Done**

- All fields are present and the styling matches the design (feedback welcome on how to improve any design patterns)

Conditional functionality and form submission done in other issues.

**Comment by indraneel** [comment]
How does authentication work when writing to this spreadsheet via API?

**Comment by emmambd** [comment]
@Alessandro100 Updated here!
