### ISSUE TITLE
Integration tests failing on QA intermittently

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#407]
Realtime municipality integration test failing on QA intermittently - need to investigate before we release on #397

**Comment by jcpitre** [comment]
The integration test stumbles on a gtfs_rt with municipality `Des Moines`:
```
AssertionError: Expected at least one feed with municipality 'Des Moines', got 0.
```
The list of feeds to tests is extracted from the sources.csv
Examining this file, I see 3 lines with gtfs_rt and Des Moines as a Municipality:
```
1769,gtfs-rt,sa,US,Iowa,Des Moines,Des Moines Area Regional Transit Authority (DART),,,,193,https://www.ridedart.com/gtfs/real-time/alerts,0,,,,https://www.ridedart.com/open-data-policy-and-terms-use,41.511765,41.732874,-93.832726,-93.466485,2022-03-15T17:41:30+00:00,,,,
1770,gtfs-rt,tu,US,Iowa,Des Moines,Des Moines Area Regional Transit Authority (DART),,,,193,https://www.ridedart.com/gtfs/real-time/trip-updates,0,,,,https://www.ridedart.com/open-data-policy-and-terms-use,41.511765,41.732874,-93.832726,-93.466485,2022-03-15T17:41:30+00:00,,,,
1771,gtfs-rt,vp,US,Iowa,Des Moines,Des Moines Area Regional Transit Authority (DART),,,,193,https://www.ridedart.com/gtfs/real-time/vehicle-positions,0,,,,https://www.ridedart.com/open-data-policy-and-terms-use,41.511765,41.732874,-93.832726,-93.466485,2022-03-15T17:41:30+00:00,,,,
```
There's also a gtfs feed with Des Moines

Yet when I connect to the QA DB, querying any feed with Municipalty `Des Moines` returns only the gtfs entry.

```
SELECT feed.*
FROM feed
JOIN locationfeed ON feed.id = locationfeed.feed_id
JOIN location ON locationfeed.location_id = location.id
WHERE location.municipality LIKE '%Des Moines%';
```
result:


![Image](https://github.com/MobilityData/mobility-feed-api/assets/106176106/ff4e985f-7ffb-4e92-8e36-e3f2e26063fb)

So something happened when filling the qa DB

**Comment by emmambd** [comment]
@jcpitre There was the wrong region in this one as flagged by a contributor, so I did modify the file name: https://github.com/MobilityData/mobility-database-catalogs/pull/361. Is that what caused the issue?

**Comment by jcpitre** [comment]
The static reference was changed from 1235 (US, Delaware, No municipality) to 183 (US, Iowa, Des Moines) on the 3 gtfs-rt feeds.
So it's certainly a factor in the problem.

**Comment by emmambd** [comment]
@jcpitre It looks like the QA DB kept the old version of the feed. 

1235 - represents all of Delaware. 183 - represents a specific municipality.

**Comment by jcpitre** [comment]
It seems the QA db was updated something 2 months ago with the github action. That would explain the error.
But it points to a problem that could recur in the future: Simply a desynchronization of the DB and sources.csv

Solutions could be:

- Populate the QA DB before each execution of the integration tests
- Keep the sources.csv that was used to populate the DB somewhere (GCP Bucket?) and use it in the integration tests instead of the most recent one
- Remember that this could happen and rerun the github action if it recurs.

**Comment by davidgamez** [comment]
> It seems the QA db was updated something 2 months ago with the github action. That would explain the error. But it points to a problem that could recur in the future: Simply a desynchronization of the DB and sources.csv
> 
> Solutions could be:
> 
> * Populate the QA DB before each execution of the integration tests
> * Keep the sources.csv that was used to populate the QA DB somewhere (GCP Bucket?) and use it in the integration tests instead of the most recent one
> * Remember that this could happen and rerun the github action if it recurs.

I vote for `Populate the QA DB before each execution of the integration tests`, this will guarantee that DB and sources.csv are in sync before running the integration tests suite.

**Comment by jcpitre** [comment]
The QA database update should be triggered when there is a change in the catalog (See [this](https://github.com/MobilityData/mobility-feed-api/blob/acf7011e6af11f1d01655f55e945842116ccecd6/.github/workflows/db-update-qa.yml#L10))
Apparently it was not triggered when https://github.com/MobilityData/mobility-database-catalogs/pull/361 was merged.

**Comment by jcpitre** [comment]
I can modify the code so the `mobility-database-catalogs` sends the `catalog-sources-updated` notification each time the `sources.csv` file is recreated. But there is no guarantee there is something new or changed in that file.
In that case mobility-feed-api will update the QA db with the new csv file.
Is this acceptable?

**Comment by davidgamez** [comment]
> I can modify the code so the `mobility-database-catalogs` sends the `catalog-sources-updated` notification each time the `sources.csv` file is recreated. But there is no guarantee there is something new or changed in that file. In that case mobility-feed-api will update the QA db with the new csv file. Is this acceptable?

If we filter the `export_to_csv` action by the `catalog` path, the data will most likely change.

**Comment by jcpitre** [comment]
What if there is a change in populate_db.py (foe example) that ends up changing the contents of the csv file?

**Comment by jcpitre** [comment]
Sorry, I meant export_to_csv.py, or the swift script.
