### ISSUE TITLE
Decide on approach for token management system

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#43]
## User Stories

-  I need a way to sign up for API access, so that I can use the API and start playing with it. 

## Acceptance Criteria

Determine an approach for token management that includes

- Sign up method (e.g Github sign in with [transitfeeds.com](https://transitfeeds.com/))
- Individual API authorization (authorization for an organization is out of scope for the MVP) 
- A method to revoke access to a token 
- Define mechanism for setting rate limits

   
## Non-Functional Requirements

- Include how we'll track usage analytics based on the API token (# of requests, how frequently different users are requesting from the API, etc) 

## Considerations

- We'll have no Web UI for this first release, so we'll need either a third party sign in (e.g Github) or form integration (e.g Google Form or Typeform) for users to sign up.

## Other Examples

- [Entur, Norway's National Access Point](https://developer.entur.org/pages-intro-authentication)

**Comment by davidgamez** [comment]
This is part of #2

**Comment by qcdyx** [comment]
We decide to go with Firebase and GCP.
