### ISSUE TITLE
Add total # of unique notices grouped by severity

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#439]
### Describe the issue 

Right now, the total # of errors, warnings, info, etc seems to be a `sum of the number of occurrences of notices with that severity`. 

Instead, it should be the # of unique notices. For example, in the dataset below, the error count should be 2, not 39399.

**Why?**

Validator users have consistently given feedback that the number of occurrences is overwhelming, and sometimes a deterrent for producers to actually fix issues, since it isn't clear that they can often fix thousands of occurrences with 1-2 changes. We want to highlight the **unique** number of validation notices triggered instead to reduce overwhelm and indicate the diversity of problems within a dataset. 

Occurrences can be added in the future, and should be included per notice, e.g `block_trips_with_overlapping_stop_times` `total_occurrences` is 4.

### Steps/Code to Reproduce

Go to Swagger: https://mobilitydata.github.io/mobility-feed-api/SwaggerUI/index.html#/

Use mdb-10-202402080058

In `/v1/datasets/gtfs/mdb-10-202402080058`

```
  "total_error": 39399,
   "total_warning": 1486333,
   "total_info": 11,
   "url_json": "https://files.mobilitydatabase.org/mdb-10/mdb-10-202402080058/report_5.0.1.json",
   "url_html": "https://files.mobilitydatabase.org/mdb-10/mdb-10-202402080058/report_5.0.1.html"
```

### Expected Results

```
  "total_error": 2,
   "total_warning": 11,
   "total_info": 1,
   "url_json": "https://files.mobilitydatabase.org/mdb-10/mdb-10-202402080058/report_5.0.1.json",
   "url_html": "https://files.mobilitydatabase.org/mdb-10/mdb-10-202402080058/report_5.0.1.html"
```

### Actual Results

In `/v1/datasets/gtfs/mdb-10-202402080058`

```
  "total_error": 39399,
   "total_warning": 1486333,
   "total_info": 11,
   "url_json": "https://files.mobilitydatabase.org/mdb-10/mdb-10-202402080058/report_5.0.1.json",
   "url_html": "https://files.mobilitydatabase.org/mdb-10/mdb-10-202402080058/report_5.0.1.html"
```

### Proposed Solution 

Add `unique_error_count`, `unique_warning_count`, `unique_info_count` so it's clear what is being described.

**Comment by jcpitre** [comment]
Tasks:

- [ ] Add total_unique_error, total_unique_warning, total_unique_info and keep total_error, total_warning, total_info
- [ ] These unique values are calculated on the fly
