### ISSUE TITLE
User should stay logged in when open new tab on Privacy Policy and Terms and Conditions

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#443]
### Describe the bug

When a user goes to the privacy policy or terms and conditions in the footer, a new tab is opened and they're no longer logged in

### Steps/Code to Reproduce

- Login at https://mobilitydatabase.org/sign-in
- Go to privacy policy and/or terms and conditions in the footer (e.g https://mobilitydatabase.org/privacy-policy) 
- Check Account navigation item in the header. It will have changed from Account to Login.

### Expected Results

User should stay logged in 

### Actual Results

User is no longer logged in

**Comment by qcdyx** [comment]
After investigating, I discovered that the issue extends beyond opening the Privacy Policy and Terms and Conditions in a new tab. It also occurs when a user opens the About page in a new tab. Additionally, if a logged in user bookmarks the login page and accesses it directly, a blank page is displayed. This indicates that we lack a global mechanism for managing user states during cold loading in our React application.
<img width="1713" alt="image" src="https://github.com/MobilityData/mobility-feed-api/assets/5789435/575ff184-0d2f-441d-8a3d-b97b3f1d5540">
<img width="1694" alt="image" src="https://github.com/MobilityData/mobility-feed-api/assets/5789435/4a48be54-e07c-4b0b-b9b2-1b4fc9ee2df7">
A new issue should be created to address and resolve this problem.

**Comment by davidgamez** [comment]
> After investigating, I discovered that the issue extends beyond opening the Privacy Policy and Terms and Conditions in a new tab. It also occurs when a user opens the About page in a new tab. Additionally, if a logged in user bookmarks the login page and accesses it directly, a blank page is displayed. This indicates that we lack a global mechanism for managing user states during cold loading in our React application. <img alt="image" width="1713" src="https://private-user-images.githubusercontent.com/5789435/344202362-575ff184-0d2f-441d-8a3d-b97b3f1d5540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODYwODIsIm5iZiI6MTcxOTU4NTc4MiwicGF0aCI6Ii81Nzg5NDM1LzM0NDIwMjM2Mi01NzVmZjE4NC0wZDJmLTQ0MWQtOGEzZC1iOTdiM2YxZDU1NDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTQ0MzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzhlYTdiM2FiZmRlOGY2NGM5MGZiN2Y1NTQ0NjY3M2M3N2Y3ZWM5YjhkY2RkMjM1OWIwNDg0NWYyNGViMmE0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.No90TtDjWs196K3MtF4O3lrslip3xLeTraKa2AVFFtI"> <img alt="image" width="1694" src="https://private-user-images.githubusercontent.com/5789435/344202486-4a48be54-e07c-4b0b-b9b2-1b4fc9ee2df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODYwODIsIm5iZiI6MTcxOTU4NTc4MiwicGF0aCI6Ii81Nzg5NDM1LzM0NDIwMjQ4Ni00YTQ4YmU1NC1lMDdjLTRiMGItYjliMi0xYjRmYzllZTJkZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTQ0MzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRlZmYxNjk2NTIyYWU5ZTJjYzNkYzA4NmZlZTFjZjJhZTBkOWE2NWIwZWJhZjE4NGZkYWY3YzIxMThhMTg0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fqt9kHmXhsHFX5MSrH0GxazeemLxmjNKnwhYy7ncZ4U"> A new issue should be created to address and resolve this problem.

Can we open the terms and conditions and the privacy policy in the same tab as a quick fix?

**Comment by qcdyx** [comment]
@davidgamez Opening the Privacy Policy and Terms and Conditions on the same page will definitely fix the issue. I recommend implementing this as a quick fix and closing the issue. @emmambd
