### ISSUE TITLE
Final GTFS Realtime feed page: Related Realtime Feeds

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#467]
Describe the problem
[Final GTFS Realtime feed page design is here](https://www.figma.com/design/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?node-id=1370-1781&m=dev)

Proposed solution: 

Please style the following sections to match the composite:

- [ ] Related Realtime Feeds 
- [ ] Call `gtfs_feeds/{id}/gtfs_rt_feeds` to retrieve a list of associated realtime feeds

These realtime feeds should be pulled based on their static reference. Any realtime feed with the same static reference as the feed displayed on the webpage should be included within this component. 

Cypress tests should be included for these sections within the PR.

**Comment by indraneel** [comment]
Hey @emmambd what does `static reference` refer to here?

**Comment by indraneel** [comment]
This is partially blocked on #420 being complete (currently the API doesn't return associated realtime feeds)

**Comment by emmambd** [comment]
@indraneel This would be a good small issue to work on before jumping back in the feed form.
