### ISSUE TITLE
Data Management Plan: Log dashboard

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#470]
### Describe the problem

# Description
The  [Data Management Plan](https://docs.google.com/document/d/1keMMNXCklNNENk-hRhHQc4uGSopRhX5C1tJHpaVCTSw/edit?usp=sharing) defines a few actions to be taken to preserve the information on the Feeds Database. To comply with the plan, the following actions need to be taken on the DB configuration per environment:

### Proposed solution

- [x] Create a Log dashboard (prod)
- [x] Include alerts when files are deleted
- [ ] Review access to DB (dev, qa, prod)

**Comment by davidgamez** [comment]
Added the following dashboards:
