### ISSUE TITLE
Testing improvement: Add integration tests with controlled data

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#488]
### Describe the problem

In #448, it was proposed to add new test _framework_ that would consists of integration tests using controlled data and an actual database.

### Proposed solution

The DB would be filled with:
- A reduced version of source.csv that we control
- The equivalent of test_datasets.json to add missing data that can reproduce error conditions

Note that you can refer to [populate_db_test_data.py](https://github.com/MobilityData/mobility-feed-api/blob/main/api/src/scripts/populate_db_test_data.py) for code that fills a DB from a json file.

The test DB should be hosted either on a local Docker container, that would let us run it from the command line, or on GCP or Github when run from a Github action.

**Comment by davidgamez** [comment]
Tasks:
 - [ ] Create all test cases in the JSON file and document them
 - [ ] Unify loading of test data. Load data only from a JSON file
 - [ ] Start tests with clean local DB and delete all entities after the complete test. Use the docker `liquibase-test` DB.
