### ISSUE TITLE
Minor API changes

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#49]
- Update `feeds/{id}/gtfs` endpoint to `feeds/gtfs/{id}` 
- Update `feeds/{id}/gtfs_rt` endpoint to `feeds/gtfs_rt/{id}`
- Update `feeds/{id}/datasets/gtfs` endpoint to `feeds/gtfs/{id}/datasets`
- Update `datasets/{id}/gtfs` endpoint to `datasets/gtfs/{id}`
- Update all filter parameters to remove `Exact syntax to be designed` 
- Update all sort parameters to remove `Exact syntax to be designed` and clarify sort semantics. Should be able to sort by`external_id` and (for GTFS feeds) `country_code`.
- Update description for `feeds/gtfs_rt` to "Get some (or all) GTFS Realtime feeds from the Mobility Database."
    - Update Response description for `feeds/gtfs_rt` to "Successful pull of the GTFS Realtime feeds info."
- Update description for /feeds/{id}/gtfs to "Get the specified GTFS feed from the Mobility Database."
- Update description for `feeds/gtfs/{id}/datasets` to "Get a list of datasets related to a GTFS feed."
- In GTFSFeeds schema, remove GBFS and GOFS as `data_type` options
- Update `features` to `components` on GtfsDataset schema. Update description to "An array of components for this dataset."
- Provider should be an array field (we can splice them into a list based on commas from the CSV)
- Remove location fields (country_code, subdivision_name, municipality) from dataset

Filters currently specified:

**feeds**

 string `filter`
      - filter options
          - contains string `provider`, e.g `"Kearns"`

**feeds/gtfs**

 filter options (should be able to filter by multiple values for each)
- contains string `provider`, e.g `"Kearns"`
- exact string `country_code`e.g `"FR"`
- contains string `subdivision_name` e.g `"Queensland"`
- contains string `municipality` e.g `"New York City"`
 - datetime `download_date`
      - greater than 1 date
      - lesser than 1 date
      - between 2 dates

**feeds/gtfs_rt**

 string `filter`
      - filter options
          - contains string `provider`, e.g `"Kearns"`
          - enum `entity_types`: options `vp`, `tu`, `sa`

**feeds/gtfs/{id}/datasets**

- filter options
    datetime `download_date`
   - greater than 1 date
   - lesser than 1 date
   - between 2 dates

**Comment by jcpitre** [comment]
Some additions to the issue:

- Add the version URL prefix (e.g. /v1/Feeds)

**Comment by jcpitre** [comment]
@emmambd If provider is an array, how can we use for sorting?

**Comment by emmambd** [comment]
@jcpitre Removed provider.

**Comment by jcpitre** [comment]
Filtering and sort options have been delegated to https://github.com/MobilityData/mobility-feed-api/issues/63
