### ISSUE TITLE
Modify data quality summary section of feed page to use unique_counts 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#490]
### Describe the problem

The data quality summary report counts for errors, warnings, and info notices should use 

- unique_error_count
- unique_warning_count
- unique_info_count 

instead of the total counts in the API response. 

### Proposed solution

Use 

- unique_error_count
- unique_warning_count
- unique_info_count

**Comment by indraneel** [comment]
Should this apply to Dataset History also?

**Comment by davidgamez** [comment]
> Should this apply to Dataset History also?

Yes, numbers should be aligned to avoid confusion. Thanks for catching this!
