### ISSUE TITLE
Discrepancies between validation report and UI 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#491]
### Describe the problem

I'm noticing some cases where the validation report information shared through the API doesn't seem to match the actual validation report when I test it through gtfs-validator.org. 

https://qa.mobilitydatabase.org/feeds/mdb-5
vs. https://gtfs-validator-results.mobilitydata.org/e988469b-3eed-40a2-b0fd-ded283a828a3/report.html

### Proposed solution

We should investigate the reason for the discrepancy.

**Comment by davidgamez** [comment]
In this case, the validation reports are not generated. It should be clear in the UI when there are no errors and when the validation reports are not _"available"_.

**Comment by davidgamez** [comment]
> @davidgamez I'd like to understand why this is happening as well - in this particular case, I don't see why we would've been unable to generate the validation report (e.g it's a real ZIP file).

@cka-y, did we generate all the reports in QA?

**Comment by cka-y** [comment]
It seems the error in QA and DEV is due to the backend services of the validator. The same thing is happening with the validator's web UI: gtfs-validator-staging.mobilitydata.org

**Comment by davidgamez** [comment]
@cka-y, can you test the validation workflows as the gtfs web validator is fixed now? Thanks!

**Comment by cka-y** [comment]
@davidgamez it is working now: https://qa.mobilitydatabase.org/feeds/mdb-5
