### ISSUE TITLE
Support multiple languages in the search endpoint

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#499]
### Describe the problem

Currently in [sources.csv](https://bit.ly/catalogs-csv), we have multiple languages represented, including English, French, Italian, German, Spanish, Polish, Portuguese. It should be possible to search for words in these languages and return a response, otherwise many international feeds will not be searchable currently.

### Proposed solution

Implement changes to the search endpoint and view configuration to support English, French, Italian, German, Spanish, Polish and Portuguese. 

### Additional context

- You can test with feeds in other languages in sources.csv, e.g mdb-686: "Société nationale des chemins de fer belges"

_No response_

**Comment by davidgamez** [comment]
The search endpoint supports matching _full_ words in any language. The provided example appears in the results. Derived words in languages other than English are not supported. Is the intention of this issue to support different languages matching on lexemes?

**Comment by emmambd** [comment]
@davidgamez When I tested the endpoint with the query "Société nationale des chemins de fer belges", I got no responses returned. Full words in any language would cover the scope of this issue.

**Comment by davidgamez** [comment]
> @davidgamez When I tested the endpoint with the query "Société nationale des chemins de fer belges", I got no feeds returned. Full words in any language would cover the scope of this issue.

Let's connect on this. I'm getting the right response from the endpoint.

<img width="1399" alt="Screenshot 2024-06-20 at 8 43 01 AM" src="https://github.com/MobilityData/mobility-feed-api/assets/1192523/0b9b9344-7615-46b4-8dd3-4a01f625f6b3">

**Comment by emmambd** [comment]
@davidgamez Ah, I see my mistake now - I kept the mdb-id in the Swagger test response. Looks good! Then I can close this issue.
