### ISSUE TITLE
Create API version in OpenAPI

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#50]
- Set up version 1.0 and/or commit hash in python package so we can do versioning in the future
- Include commit hashes to the Open API version endpoint

**Comment by indraneel** [comment]
@davidgamez is this still needed? if so, can you elaborate a bit?

**Comment by davidgamez** [comment]
Hi @indraneel, the intention here is to be able to verify the deployed API version. Currently, the metadata endpoint returns the version of the deployed API(https://github.com/MobilityData/mobility-feed-api/blob/e9b1cfc7feb9ee30a501cc9989eea9e1b99e353c/docs/DatabaseCatalogAPI.yaml#L569). The implementation has hardcoded the version number(https://github.com/MobilityData/mobility-feed-api/blob/e9b1cfc7feb9ee30a501cc9989eea9e1b99e353c/api/src/feeds/impl/metadata_api_impl.py#L12). It would be nice if this can be changed by a `"dynamic"` value resulted from a `release` phase from the GitHub pipeline. A second task is to add the commit hash obtained on a running GH action.

**Comment by qcdyx** [comment]
Tasks:
- [ ] every time we package the code, we get the commit hash from the git repository, and write it to json file 
- [ ] get version when we do release/pre release, we modify the json file
