### ISSUE TITLE
Programmatic download of valid ZIP files returns HTML responses for certain producer URLs

### ISSUE THREAD

**Issue by cka-y** [MobilityData/mobility-feed-api#502]
Most skipped datasets are not valid ZIP files. However, there are a few cases where accessing the `producer_url` via a web browser successfully downloads a valid ZIP file, but programmatically attempting to replicate this process results in an HTML file instead. An example for `mdb-683` returns:

```html
<html>
<head><title>410 Gone</title></head>
<body>
<center><h1>410 Gone</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

Here is a list of stable IDs and producer URLs where this issue is known to occur (note that there may be others):

- [mdb-232](https://www.fnsb.gov/DocumentCenter/View/690/General-Transit-Feed-Specification-ZIP) (returns an empty response when accessed programatically with 200 status code)
- [mdb-919](https://www.cityoflompoc.com/home/showdocument?id=29896) (returns an HTML file when accessed programatically with 403 status code)
- [mdb-683](https://dipl.nt.gov.au/data-feeds/bus-gtfs/google-transit-alice-springs.zip?v=0.7.0) (returns an HTML file when accessed programatically with 200 status code)

_Originally posted by @cka-y in https://github.com/MobilityData/mobility-feed-api/issues/501#issuecomment-2179251192_

**Comment by emmambd** [comment]
Potentially related to https://github.com/MobilityData/mobility-database-catalogs/issues/216

**Comment by davidgamez** [comment]
Timebox: _1 day_
