### ISSUE TITLE
Investigate how to recognize that a dataset was unfetchable

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#506]
### Describe the problem

We need to be able to track the status/availability of datasets. We need to be able to track when a dataset was not fetched because it was not a valid ZIP file. This should then enable/unblock #505 for us to be able to label which feeds have never returned a valid dataset. 

### Proposed solution

Determine solution for how to store and log when datasets were not fetchable.

**Comment by cka-y** [comment]
Closing this
Follow up issues: #529 and #530
