### ISSUE TITLE
Change dataset check frequency to every 4 days 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#518]
### Describe the problem

Based on findings in https://github.com/MobilityData/mobility-database-catalogs/issues/375#issuecomment-2189015623, we should update our dataset check frequency to every 4 days. 

### Proposed solution

- Update dataset update processing to every 4 days rather than once a week 
- Catalogs repo should be updated to store every 4 days rather than daily

**Comment by davidgamez** [comment]
It might not be trivial to track when the update tasks are executed every four days. We can set the frequency to two days per week with fixed weekdays, for example, Monday and Thursday. This will predictably cover a period of 3 and 4 days.

**Comment by emmambd** [comment]
Reopening since I think the catalogs part of the work still has to be done - correct @cka-y?
