### ISSUE TITLE
Add created_at timestamp to feed response

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#533]
### Describe the problem

In order to track what feeds have been added over time, we need to add a created_at timestamp to a feed. 

### Proposed solution

- Add created_at timestamp to a feed, including serving it in the feeds, gtfs and gtfs-rt feed responses. Description should state that this timestamp is when it was added to the Mobility Database backend. 
- Manually updated the created_at timestamps for previous feeds. [Spreadsheet of dates after February 8th here.](https://docs.google.com/spreadsheets/d/1OXTycXAzkrITgSVNI-skr9p-ADOojrJa_dhQt-z64_k/edit?usp=sharing)

**Comment by cka-y** [comment]
Tasks:
- [ ] Modify DB schema
- [ ] Modify populate script
- [ ] Modify API response
- [ ] Add/modify unit test
- [ ] Create sql script to manually update existing feeds
