### ISSUE TITLE
Update transitfeeds.com to reference the new API

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#54]
On https://transitfeeds.com/

- Update "Sign in with Github" to "Register for the new API" with https://mobilitydatabase.org/sign-up
- Update "Report a Data Issue" link to point to https://github.com/MobilityData/mobility-database-catalogs
- Update API page with new text: 

"If you would like to use the new API with up-to-date GTFS feeds, go to https://mobilitydatabase.org/. The old TransitFeeds API can still be used for accessing historical data."

https://transitfeeds.com/about
- Update Submit a feed or report an issue to point to https://github.com/MobilityData/mobility-database-catalogs

Banner on all pages
- Update "TransitFeeds data is not regularly updated. Find up-to-date GTFS Schedule data on the [the Mobility Database catalogs](https://database.mobilitydata.org/)." to "TransitFeeds data is not updated. Find up to date GTFS data on [the Mobility Database catalogs with the spreadsheet or API.](https://mobilitydatabase.org) "

[Comp design here](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms-Form?type=design&node-id=143%3A2&mode=design&t=dl9QQtMTVQkQwKlh-1)

**Comment by fredericsimard** [comment]
All done ✅
