### ISSUE TITLE
Clean QA database and run health check in PROD

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#561]
# Description
QA contains inconsistent data as we have been testing new and unstable code in QA. We need to make sure all data is consistent to be able to execute manual testing with healthy data in QA. In addition, let's do a healthy check on prod to make sure all inconsistent data in QA is due to unstable code not bug within the data pipeline.

 - All feeds with datasets must have one dataset marked as the latest.
 - All valid latest datasets that should have a validation report generated
 - All valid latest datasets that  should have bounding box information generated

**Comment by qcdyx** [comment]
Script to create a tunnel:
./scripts/tunnel-create.sh -project_id mobility-feeds-qa -zone northamerica-northeast1-a -instance bastion-instance-qa -target_account it -db_instance mobilitydata-database-instance -port 9902

./scripts/tunnel-create.sh -project_id mobility-feeds-prod -zone northamerica-northeast1-a -instance bastion-instance-prod -target_account it -db_instance mobilitydata-database-instance -port 9901

**Comment by qcdyx** [comment]
1. All feeds with datasets must have one dataset marked as the latest.
There are 52 feeds in production that lack a latest dataset.

2. All valid latest datasets that should have a validation report generated
There are 3 latest datasets that lack a validation report.

3. All valid latest datasets that should have bounding box information generated
There are 52 latest datasets that lack bounding box info.

**Comment by qcdyx** [comment]
All data in PROD meet the first two criteria. Similarly, in QA, all but one dataset meet the second criterion.
https://github.com/MobilityData/mobility-feed-api/issues/589
We need to create a cloud function in batch for updating bounding box info for all valid latest datasets.
https://github.com/MobilityData/mobility-feed-api/issues/590
