### ISSUE TITLE
API filtering on entity type doesn't work 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#599]
### Describe the bug

Verify successful retrieval of GTFS Realtime feeds with various combinations of parameters.

Entity_types
For query: https://api-qa.mobilitydatabase.org/v1/gtfs_rt_feeds?entity_types=vp
Got all gtfs_rt feeds in response regardless of the entity type
Mix. e.g. provider nashville and entity_type tu
Same problem as previous query, the filtering on entity_types does not work
E.g.2 provider nashville and subdivision Rhode

### Steps/Code to Reproduce

See above

### Expected Results

Does not retrieve feeds

### Actual Results

See above

**Comment by jcpitre** [comment]
Tasks:
- Fix bug
- Add unit test
