### ISSUE TITLE
Testing with a non-existing feed id results in an empty array instead of a HTTP 404 response

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#600]
### Describe the bug

Testing with a non-existing feed id results in an empty array instead of a HTTP 404 response

### Steps/Code to Reproduce

Testing with a non-existing feed id results in an empty array instead of a HTTP 404 response

### Expected Results

See above

### Actual Results

See above

**Comment by jcpitre** [comment]
Tasks:
- Correct the problem
- Add a unit test
