### ISSUE TITLE
Filter out deprecated feeds from search

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#612]
### Describe the problem

It's confusing to see deprecated feeds in the search result.

### Proposed solution

Filter out deprecated feeds from the search page. Users can still navigate to the deprecated feed if it's linked or they search it on their own.

**Comment by jcpitre** [comment]
Add a parameter with the list of status we want.

**Comment by jcpitre** [comment]
@emmambd currently I don't plan to add a UI element that would let a user ask for deprecated feeds. So there will be no way to list them in the UI, for now. Is this acceptable?

**Comment by emmambd** [comment]
@jcpitre Yes! We want to filter them out for now, no option to select them.

**Comment by emmambd** [comment]
Since @jcpitre, would it make sense for someone else to take on finishing this? cc @davidgamez

**Comment by davidgamez** [comment]
> Since @jcpitre, would it make sense for someone else to take on finishing this? cc @davidgamez

The PR will be ready for review soon ;-)
