### ISSUE TITLE
Include full list of transit providers included in the feed summary section in cases where there are multiple 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#615]
### Describe the problem

Include full list of transit providers included in the feed summary section in cases where there are multiple. 

We identify "multiple" transit providers based on comma separation.

### Proposed solution

- Page heading: only 1 transit provider displayed with "[provider name] and [number of other providers] others"
- Search result: "[transit provider name] plus [number of other providers]"
     - See more button to display full list of transit providers in the provider column
- Individual feed page: when there are 4 or fewer transit providers associated with a feed, [display the list in the Feed Summary as shown here](https://www.figma.com/design/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?node-id=1370-1563&t=Ugpk1LmQHw1JlW1v-1). No "see full list" option
- Individual feed page: when there are 5+ transit providers associated with a feed, include a collapsible bulleted list [(as shown here)](https://www.figma.com/design/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?node-id=2839-10271&t=Ugpk1LmQHw1JlW1v-1)
- For mobile, will likely need to make the transit provider list 1 column rather than 2

**Comment by emmambd** [comment]
@Alessandro100 There are cases where 1 feed has dozens of transit providers, (e.g mdb-1090), so I'd like to give some thought to how to visually display this. When you return from vacation, let's have a meeting on it!

**Comment by davidgamez** [comment]
Tasks:
- Add the _see full list_ feature 
- Sort in alphabetical order the list of providers
- Change header and page title 
- Modify the search rendering to include only the first provider with the total if the additional providers.
