### ISSUE TITLE
Create a Contact Us screen

### ISSUE THREAD

**Issue by qcdyx** [MobilityData/mobility-feed-api#619]
### Describe the problem

Currently, clicking on "Contact Us" in the header opens the default mail application on the user's computer. If the user doesn't have a default mail application set, it opens a new tab in the browser. 

### Proposed solution

We should implement a "Contact Us" screen that includes a hyperlinked email address, a copy button, and instructions on how to join the Mobility Data Slack.

[Rough composite here](https://www.figma.com/design/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?node-id=3036-11214&m=dev)

**Comment by emmambd** [comment]
@emmambd to add design

**Comment by davidgamez** [comment]
Tasks:
- [ ] Render email and contact information in the page
