### ISSUE TITLE
Automate locations: Modify the API response for the feed 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#622]
### Describe the problem

Related to #618 

Modify the GTFS API response for the feed to set the location as the latest dataset location if that dataset exists; otherwise, resort to the location information extracted from the mobility-database-catalog.

### Proposed solution

Includes integration tests

**Comment by cka-y** [comment]
Address comment: https://github.com/MobilityData/mobility-feed-api/pull/642#issuecomment-2263342173 to make sure database updates are not blocked in PROD
