### ISSUE TITLE
Design filtering options for REST API.

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#63]
### Describe the problem

In #49 we made some adjustments to the API. 
This was supposed to include filtering options but it was not done. 
I transferred the filtering part of the original issue here:

**feeds**

 string `filter`
      - filter options
          - contains string `provider`, e.g `"Kearns"`

**feeds/gtfs**

 filter options (should be able to filter by multiple values for each)
- contains string `provider`, e.g `"Kearns"`
- exact string `country_code`e.g `"FR"`
- contains string `subdivision_name` e.g `"Queensland"`
- contains string `municipality` e.g `"New York City"`
 - datetime `download_date`
      - greater than 1 date
      - lesser than 1 date
      - between 2 dates

**feeds/gtfs_rt**

 string `filter`
      - filter options
          - contains string `provider`, e.g `"Kearns"`
          - enum `entity_types`: options `vp`, `tu`, `sa`

**feeds/gtfs/{id}/datasets**

- filter options
    datetime `download_date`
   - greater than 1 date
   - lesser than 1 date
   - between 2 dates

### Proposed solution

Here are some suggestions:

- Example of filtering in REST api:
      - https://agileappscloud.info/aawiki/REST_API:Filter_Expressions_in_REST_APIs

- An in-house developed syntax for MVP (minimum viable product):
   - e.g. /feeds/gtfs/?filter=provider~mta&status=active
      - Use and ! (not), & (and) and | (or). These characters will need to be escaped since they are reserved for URIs.
      - Priority is !, &, then |.
      - Tests are:
         - =: exact value (all types)
         - <, >, <=, >=: 
            - Used for numerical fields and dates.
            - Error for strings (for MVP’s sake)
            ~: For strings only. field contains the string 

   - We need to make sure we can beef this up later (after MVP) and not introduce contradictions. We could later
      - Add parenthesis
      - Add regex
      - etc

- Github syntax:
   - They have a separate endpoint for search [link](https://docs.github.com/en/free-pro-team@latest/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests)
      - e.g. https://api.github.com/search/issues?q=Q
   - Elaborate search syntax: [link](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax)

- oData
  - [link](https://learn.microsoft.com/en-us/odata/concepts/queryoptions-overview)
  - Here is a oData filter parser done in javascript. https://github.com/jadrake75/odata-filter-parser/blob/master/doc/Intro.md. This could help us jumpstart the filter implementation. Maybe there's something similar for python?

**Comment by indraneel** [comment]
Here's a filter library for FastAPI: https://github.com/arthurio/fastapi-filter 

Of the above suggestions, it is probably most similar to the in-house syntax. 

> By default, fastapi_filter supports the following operators:
> 
> neq
> gt
> gte
> in
> isnull
> lt
> lte
> not/ne
> not_in/nin
> like/ilike

**Comment by indraneel** [comment]
opened #92 to track work on this
