### ISSUE TITLE
Add latest dataset metadata to feed response

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#66]
### Describe the problem

- If I want to just check a feed and re-pull the `hosted_URL` each time there's a new dataset or the URL is changed, right now I have no way of seeing when the hosted_URL has been updated. 

### Proposed solution

- Add `downloaded_at`(~~`updated_at`~~)( field in latest_dataset object in all feeds endpoints to track when a log was made (that way I know the feed's been changed and I should refresh my data).
- Add dataset `hash` to `latest_dataset` object in feed response

**Comment by davidgamez** [comment]
Tasks:
- [ ] Update OpenAPI schema.
- [ ] Refactor feed's endpoint.

**Comment by jcpitre** [comment]
@emmambd I'm having second thoughts about `downloaded_at`. The __at_ suffix is OK if we specify a time (downloaded at 3PM for example) but for a date doesn't `downloaded_on` be more appropriate? (downloaded on the 4th of July).

Nitpicking maybe, but I would hate to be stuck forever with a syntax that doesn't feel quite right.

**Comment by emmambd** [comment]
@jcpitre Based on Arda's PR: https://github.com/MobilityData/mobility-feed-api/pull/262 it's a timestamp, so it'll have both a date and time. Does it still seem off to you?

**Comment by jcpitre** [comment]
> [@jcpitre](https://github.com/jcpitre) Based on Arda's PR: [#262](https://github.com/MobilityData/mobility-feed-api/pull/262) it's a timestamp, so it'll have both a date and time. Does it still seem off to you?

Yes. I guess there is no perfect solution. `download_timestamp`? Kind of a mouthful.

**Comment by emmambd** [comment]
Decision: leave downloaded_at as is.
