### ISSUE TITLE
Empty search query with no additional parameter returns  HTTP 500

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#687]
### Describe the bug

The search endpoint returns HTTP 500 Internal error when search_query is empty and no additional parameter is passed

### Steps/Code to Reproduce

```
curl --location 'https://api-qa.mobilitydatabase.org//v1/search?search_query=' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer REPLACE_ME_WITH_ACCESS_TOKEN'
```

### Expected Results

Returns all the feeds.

### Actual Results

HTTP 500 error is returned.

**Comment by Alessandro100** [comment]
To note: This is only happens in postman, not doable in UI
