### ISSUE TITLE
Missing `country` value in location entities with no extracted location data

### ISSUE THREAD

**Issue by cka-y** [MobilityData/mobility-feed-api#694]
### Describe the bug

GTFS feeds with no extracted location data and their corresponding GTFS RT feeds are resulting in an empty `country` field for the associated `Location` entity in the database. In cases where a `country` value is present, it is because the extracted location matches an existing location (`location_id`), automatically setting the `country` value. However, this behavior is inconsistent across the database, leading to missing `country` values for many `Location` entities. This affects the search results when searching by country name.

**Comment by Alessandro100** [comment]
API

Tasks
[]  Fix the populate script to auto populate the missing country names and over-write the existing ones (On the feed and dataset)

**Comment by cka-y** [comment]
[List of feed's stable ids that have no country name](https://github.com/user-attachments/files/16661727/feeds_w_no_country.csv)
