### ISSUE TITLE
Add Ids to gtfs Features

### ISSUE THREAD

**Issue by Alessandro100** [MobilityData/mobility-feed-api#733]
Gtfs features currently do not have a unique way to identify themselves. We need a way to uniquely identify features so that we can
- attach and use data with them reliably

We will need to add an id to the gtfs feature table

thoughts
- should we also add extra data to the features in the db? info url, category.. and in the frontend make an api call to get feature data?

**Comment by qcdyx** [comment]
Tasks:

- [ ] In the case of 1 to 1 relationship, keep a mapping of key - values, if name is changes, just update the values
- [ ] In the case of splitting features, we add new features

**Comment by emmambd** [comment]
Need to review and approve #1812 before working on this so our features list is final

**Comment by emmambd** [comment]
Unblocked. Should use new features as written in https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md
