### ISSUE TITLE
Generate validator analytics from our API pipeline

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#753]
### Describe the problem

Generate validator analytics from our API pipeline

### Proposed solution

[Analytics report that includes information similar to 5.0 release](https://docs.google.com/spreadsheets/d/10zGOwbqbpdc-rhZ1UIDAqC8N9dnjh5fnViF1rBYOEwg/edit?gid=0#gid=0)

**Comment by davidgamez** [comment]
Tasks:
- Execute transfer report function(manually)
- Create a Big Query Query to extract the metrics. Review current query
- Create connection between Gsheet and the BQ query.
- Document the new process.
