### ISSUE TITLE
Update pipeline to automatically generate dataset after merge, not wait till Monday and Thursday

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#762]
### Describe the problem

When a feed is merged from the catalogs repo, we have to wait till Monday or Thursday at 12am for the dataset to actually be fetched and for the page on the website to display the data quality report. This is not ideal for reporting back to contributors that their feed has been added. 

### Proposed solution

Update the pipeline so that the dataset creation flow automatically runs when the feed is created.

**Comment by cka-y** [comment]
Tagging this as a bug as this feature already exists, but just haven't been working lately
