### ISSUE TITLE
Add official field to Add a Feed form

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#795]
### Describe the problem

Modify add feed form so users are prompted to state that the feed is the official source of information by the transit provider and should be used to display to riders. Should be asked on the third page.

### Proposed solution

See above

**Comment by davidgamez** [comment]
Tasks:
- Add the official _required_ check on the first page. Options: Yes, No, _I'm not sure_ => default empty
- Modify the Firebase function for persistent new information
- Modify the GoogleSheet (dev prod qa)
- Modify the Slack message to reflect whether the feed is official.
