### ISSUE TITLE
Searching `motionbuscard` causes a blank screen and breaks further searches

### ISSUE THREAD

**Issue by cka-y** [MobilityData/mobility-feed-api#799]
### Describe the bug

After searching for `motionbuscard` in the Mobility Database web interface, the application displays a blank screen. Subsequent searches return the same blank screen, indicating an unresolved error.

### Steps/Code to Reproduce

1. Open [mobilitydatabase.org](http://mobilitydatabase.org).
2. Search for `motionbuscard`.
3. Return to the home page.
4. Attempt to search for anything else.

### Expected Results

The search should yield results or indicate "no results" if none are found, with the ability to perform further searches.

### Actual Results

A white (blank) page appears after the initial search for "motionbuscard," persisting for any subsequent search attempts. Errors are displayed in the console.

### Additional notes

I believe that mdb-1920 (having `motionbuscard` provider) is causing issues because a lot of its fields are set as unknown in the catalog repo

**Comment by davidgamez** [comment]
The API returns location `null`, and the UI is not protected against null values.

![Image](https://github.com/user-attachments/assets/9e1327f4-9d11-4c29-84f9-a4ceaf11c49d)
