### ISSUE TITLE
Renaming API endpoints to resolve conflicting subpaths

### ISSUE THREAD

**Issue by indraneel** [MobilityData/mobility-feed-api#84]
### Describe the problem

- `/feeds/{id}` and `/feeds/gtfs` conflict because `{id}` is a string, but so is `gtfs`
- there is a design goal to have `feeds/` be an endpoint that returns every type of feed, including future ones

### Proposed solution

- One proposed fix is what @aronza has done here: https://github.com/MobilityData/mobility-feed-api/compare/main...arda/fix-api-conflict 
- - this renames `feeds/gtfs/` to `gtfs-feeds/`, and so on for the remaining current sub-paths of `feeds/`
- - preserves `feeds/` as is   

### Alternatives you've considered

Something like `feeds/id/gtfs` and `feeds/{id}/gtfs-rt`

**Comment by emmambd** [comment]
I'm in support of this solution, as was @jcpitre I believe before his vacation. cc @qcdyx and @cka-y in case there's any outstanding strong opinions on our side.

**Comment by indraneel** [comment]
Assigning to @aronza to open a PR w/ above changes
