### ISSUE TITLE
Define semantics for dataset IDs

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#9]
## **User Story**

As an API consumer, I need stable dataset IDs that I can easily cross reference with what's already in my system, so I add and update the right ones. 

## **Acceptance Criteria**

A proposed design for dataset IDs that 
- can scale to accommodate 100,000+ datasets

## **Considerations and Materials**

Possible relevant information to include in a dataset ID
- Feed ID 
- Upload date 

Other dataset IDs approaches from
- [Transit.Land: hash](https://www.transit.land/documentation/rest-api/feed_versions)
- TransitFeeds: timestamp (e.g https://transitfeeds.com/p/128-business-council/763/20170829/download) 
- [Transport Data Gouv: hash](https://transport.data.gouv.fr/api/datasets)

**Comment by qcdyx** [comment]
Final Decision: Dataset ID has an automatic-increasing ID; dataset doesn't have a stable ID, but has a reference to the Feed ID
