### ISSUE TITLE
Implement fastapi-filter

### ISSUE THREAD

**Issue by indraneel** [MobilityData/mobility-feed-api#92]
### Describe the problem

as per discussion on #63, filtering is a requirement for the various API endpoints.

### Proposed solution

This issue is for work around implementing `fastapi-filter` https://github.com/arthurio/fastapi-filter a FastAPI plugin that fits the minimum

### Alternatives you've considered

This is not oData syntax or similar. If that becomes a requirement later on, this work will not be sufficient.

**Comment by aronza** [comment]
@indraneel implementation is ready at https://github.com/MobilityData/mobility-feed-api/tree/arda/add-api-filter.

I will open a pull request once our previous one is merged: https://github.com/MobilityData/mobility-feed-api/pull/90
