### ISSUE TITLE
Add filtering on dates for feeds

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#96]
### Describe the problem

As of https://github.com/MobilityData/mobility-feed-api/pull/90 (but really https://github.com/MobilityData/mobility-feed-api/pull/94) we have filtering on feeds and datasets.

For datasets we have filtering on dates with the `downloaded_date_gte` and `downloaded_date_lte` query parameters.

We should have a similar filtering on feeds. 

### Proposed solution

We need to add a date field in the feed table
Then then add the filtering to the API.

Unclear at this time if we should have a `created_at` or `updated_at` field, or both.

**Comment by emmambd** [comment]
After discussion, we've decided not to include filtering on dates for feeds, it will just be returned in the response.
