### ISSUE TITLE
Setup prod environment for API 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#98]
We need the production environment for the API: api.mobilitydatabase.org. 

Acceptance Criteria: 

- Prod environment exists
- Environment is included in https://mobilitydata.github.io/mobility-feed-api/SwaggerUI/index.html#/

**Comment by davidgamez** [comment]
Tasks:

**Comment by davidgamez** [comment]
Reopening as it's was only partially fixed by #140
